name: Update SHTJK Currency Rates

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-rates:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4

      - name: Update rates
        run: |
          python scripts/update_rates.py

      - name: Save rates.json
        run: |
          git config user.name "SHTJK Bot"
          git config user.email "actions@github.com"

          git add api/rates.json

          git diff --cached --quiet || git commit -m "Update currency rates"

          git push